import "./globals.css";
import { Space_Mono } from "next/font/google";

const monospace = Space_Mono({
  weight: "700",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monospace.className}>{children}</body>
    </html>
  );
}
