import "./globals.css";
import { monospace } from "./constants";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monospace.className}>{children}</body>
    </html>
  );
}
